export const PATHS = {
  HOME: '/',
  LANDING: '/landing',
  AUTH: '/auth',
  RESET_PASSWORD: '/reset-password',
  VIRTUAL_PHOTOSHOOT: '/virtual_photoshoot',
  STYLE_SCENE: '/stylescene',
  ASSET_GENERATOR: '/asset_generator',
  CATALOG_FORGED: '/catalog_forged',
  POSE_MIMIC: '/pose_mimic',
  GALLERY: '/gallery',
  ASSET_COLLECTION: '/asset_collection',
  PRICING: '/pricing',
  PROFILE: '/profile',
  SETTINGS: '/settings',
  ABOUT: '/about',
  MODEL_GALLERY: '/model_gallery',
  BACKGROUND_GALLERY: '/background_gallery',
  USAGE_ANALYTICS: '/usage_analytics',
  PRIVACY_POLICY: '/privacy-policy',
  TERMS_AND_CONDITIONS: '/terms-and-conditions',
  CONTACT: '/contact',
};